services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes: 
      - ./dump/:/var/lib/mysql
    container_name: db
    networks:
      - app-network

  php-apache:
    build: Dockerfiles/php-apache/
    container_name: App_votacion
    env_file:
      - .env
    depends_on:
      - db
    volumes: 
      - ./www/:/var/www/html
    ports:
      - ${PHP_PORT}:80
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_votacion
    depends_on:
      - db
    restart: always
    ports:
      - ${PMA_PORT}:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - app-network

networks:
  app-network:
    name: aphd-2025_app-network
    driver: bridge
